[package]
name = "archivelib-sys2"
build = "build.rs"
version = "0.1.0"
authors = ["Opal Symes <leesdolphin@gmail.com>"]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
bindgen = "*"
