[package]
name = "archivelib"
description = "An implementaton of the Greenleaf ArchiveLib compression/decompression algorithm"
version = "0.1.2"
authors = ["Opal Symes <code@opal.codes>"]
edition = "2018"

homepage = "https://github.com/software-opal/archivelib-rs"
license = "GPL-2.0-only"

[workspace]
members = [
  # "archivelib-sys",
  "archivelib-sys2",
  "cli",
  "fuzz",
]

[dependencies]
failure = "0.1.3"
failure_derive = "0.1.3"
num = "0.2"

[dev-dependencies]
rand = "0.6.1"
proptest = "0.8.7"
# archivelib-sys = { version = "0.1.0", path = "archivelib-sys" }
archivelib-sys = { version = "0.1.0", path = "archivelib-sys2" }

[features]
new_impl = []

default=["new_impl"]
