[package]
name = "archivelib-sys"
build = "build.rs"
version = "0.1.0"
authors = ["Opal Symes <leesdolphin@gmail.com>"]
edition = "2018"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
bindgen = "*"

[dev-dependencies]
rand = "0.6.1"
