name: Lint

on: [push]

jobs:
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Versions
        run: |
          rustc --version
          cargo --version
          cargo clippy -- --version
      - name: Check `cargo check`
        run: |
          cargo check --all --bins --lib --examples --tests --profile test
          # rm -rfv target/*/build/archivelib*
          # rm -rfv target/*/.fingerprint/archivelib*
          rm -rfv target/*/incremental
      - name: Check `cargo clippy`
        run: cargo clippy --all --bins --lib --examples --tests --profile test
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Versions
        run: |
          rustc --version
          cargo --version
          cargo fmt -- --version
      - name: Check `cargo format`
        run: cargo fmt --all -- --check
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install deps
        run: |
          pip install poetry
          poetry install
          poetry run pip freeze
      - name: black
        run: poetry run black --py36 --check --diff .
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install deps
        run: |
          pip install poetry
          poetry install
          poetry run pip freeze
      - name: black
        run: poetry run isort --check-only --recursive --diff .
