name: Lint

on: [push]

jobs:
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Versions
        run: |
          rustc --version
          cargo --version
          cargo clippy -- --version
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all
      - name: Check `cargo format`
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install deps
        run: |
          pip install poetry
          poetry install
          poetry run pip freeze
      - name: black
        run: poetry run black --py36 --check --diff .
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install deps
        run: |
          pip install poetry
          poetry install
          poetry run pip freeze
      - name: black
        run: poetry run isort --check-only --recursive --diff .
